/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yaopaine_andfix_jni_HelloJniUtils */

#ifndef _Included_com_yaopaine_andfix_jni_HelloJniUtils
#define _Included_com_yaopaine_andfix_jni_HelloJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yaopaine_andfix_jni_HelloJniUtils
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_yaopaine_andfix_jni_HelloJniUtils_add
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_yaopaine_andfix_jni_HelloJniUtils
 * Method:    div
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_yaopaine_andfix_jni_HelloJniUtils_div
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     com_yaopaine_andfix_jni_HelloJniUtils
 * Method:    isNative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_yaopaine_andfix_jni_HelloJniUtils_isNative
  (JNIEnv *, jclass);

/*
 * Class:     com_yaopaine_andfix_jni_HelloJniUtils
 * Method:    getMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yaopaine_andfix_jni_HelloJniUtils_getMessage
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
